[package]
name = "chem"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.14.2" }
bevy_simple_text_input = "0.8.0"
bevy_mod_picking = "0.20.1"
wasm-bindgen = "0.2.95"
